apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashbox-zoo-deployment
  labels:
    app: cashbox-zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cashbox-zoo
  template:
    metadata:
      labels:
        app: cashbox-zoo
    spec:
      containers:
      - name: cashbox-zoo
        image: vecheren/cashbox_zoo
        ports:
        - containerPort: 8080
        env: 
        - name: PG_DB_NAME
          valueFrom: 
            secretKeyRef:
              name: secret
              key: pg_db_name
        - name: PG_USER
          valueFrom: 
            secretKeyRef:
              name: secret
              key: pg_user
        - name: PG_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret
              key: pg_pass
        - name: TOKEN
          valueFrom: 
            secretKeyRef:
              name: secret
              key: token
        - name: WEBHOOK_SECRET
          valueFrom: 
            secretKeyRef:
              name: secret
              key: webhook_secret
        - name: USE_POLLING
          valueFrom:
            configMapKeyRef:
              name: config
              key: USE_POLLING
        - name: SECRETS_IN_FILE
          valueFrom:
            configMapKeyRef:
              name: config
              key: SECRETS_IN_FILE
        - name: ZOO_WEBHOOK_PATH
          valueFrom:
            configMapKeyRef:
              name: config
              key: ZOO_WEBHOOK_PATH
        - name: ZOO_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: ZOO_HOST
        - name: ZOO_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: ZOO_PORT
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_URL
---
apiVersion: v1
kind: Service
metadata:
  name: cashbox-zoo-service
spec:
  type: NodePort
  selector:
    app: cashbox-zoo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100